// Generated by gencpp from file motor_control_2/motor_output.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_2_MESSAGE_MOTOR_OUTPUT_H
#define MOTOR_CONTROL_2_MESSAGE_MOTOR_OUTPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control_2
{
template <class ContainerAllocator>
struct motor_output_
{
  typedef motor_output_<ContainerAllocator> Type;

  motor_output_()
    : speed(0.0)
    , rev(0.0)
    , direction()  {
    }
  motor_output_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , rev(0.0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _rev_type;
  _rev_type rev;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::motor_control_2::motor_output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control_2::motor_output_<ContainerAllocator> const> ConstPtr;

}; // struct motor_output_

typedef ::motor_control_2::motor_output_<std::allocator<void> > motor_output;

typedef boost::shared_ptr< ::motor_control_2::motor_output > motor_outputPtr;
typedef boost::shared_ptr< ::motor_control_2::motor_output const> motor_outputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control_2::motor_output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control_2::motor_output_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control_2::motor_output_<ContainerAllocator1> & lhs, const ::motor_control_2::motor_output_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.rev == rhs.rev &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control_2::motor_output_<ContainerAllocator1> & lhs, const ::motor_control_2::motor_output_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motor_control_2::motor_output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control_2::motor_output_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control_2::motor_output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control_2::motor_output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control_2::motor_output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control_2::motor_output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control_2::motor_output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "159eef3b3a7301d5db300a5f487bda11";
  }

  static const char* value(const ::motor_control_2::motor_output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x159eef3b3a7301d5ULL;
  static const uint64_t static_value2 = 0xdb300a5f487bda11ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control_2::motor_output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control_2/motor_output";
  }

  static const char* value(const ::motor_control_2::motor_output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control_2::motor_output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n"
"float32 rev\n"
"string direction\n"
;
  }

  static const char* value(const ::motor_control_2::motor_output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control_2::motor_output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.rev);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control_2::motor_output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control_2::motor_output_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "rev: ";
    Printer<float>::stream(s, indent + "  ", v.rev);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_2_MESSAGE_MOTOR_OUTPUT_H
