// Generated by gencpp from file motor_control_2/motor_input.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_2_MESSAGE_MOTOR_INPUT_H
#define MOTOR_CONTROL_2_MESSAGE_MOTOR_INPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control_2
{
template <class ContainerAllocator>
struct motor_input_
{
  typedef motor_input_<ContainerAllocator> Type;

  motor_input_()
    : value(0.0)
    , time(0.0)  {
    }
  motor_input_(const ContainerAllocator& _alloc)
    : value(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef float _value_type;
  _value_type value;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::motor_control_2::motor_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control_2::motor_input_<ContainerAllocator> const> ConstPtr;

}; // struct motor_input_

typedef ::motor_control_2::motor_input_<std::allocator<void> > motor_input;

typedef boost::shared_ptr< ::motor_control_2::motor_input > motor_inputPtr;
typedef boost::shared_ptr< ::motor_control_2::motor_input const> motor_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control_2::motor_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control_2::motor_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control_2::motor_input_<ContainerAllocator1> & lhs, const ::motor_control_2::motor_input_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control_2::motor_input_<ContainerAllocator1> & lhs, const ::motor_control_2::motor_input_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motor_control_2::motor_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control_2::motor_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control_2::motor_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control_2::motor_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control_2::motor_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control_2::motor_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control_2::motor_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74f8c6fdf5012f9d9f480b319a08e976";
  }

  static const char* value(const ::motor_control_2::motor_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74f8c6fdf5012f9dULL;
  static const uint64_t static_value2 = 0x9f480b319a08e976ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control_2::motor_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control_2/motor_input";
  }

  static const char* value(const ::motor_control_2::motor_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control_2::motor_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 value\n"
"float64 time\n"
;
  }

  static const char* value(const ::motor_control_2::motor_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control_2::motor_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control_2::motor_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control_2::motor_input_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_2_MESSAGE_MOTOR_INPUT_H
